INSERT INTO public.users (user_name, password, email, phone, role) VALUES ('admin', '$2a$12$.1zE7l.WdGRd8CqDiFkILuxyP.xHHGVsthhEfaRZV/gZwWsycuV7S', 'shopadmin@gmail.com', '+74395943821', 'superuser' ) ON CONFLICT DO NOTHING ;
INSERT INTO public.users (user_name, password, email, phone, role) VALUES ('testuser', '$2a$12$Ciow2WbWPWCv1ICIiga7ZOmfzDY4Qaey8.GzWwceTnm2/.0zkvC7W', 'testuser@mail.ru', '+70349482038', 'user' ) ON CONFLICT DO NOTHING ;

INSERT INTO public.book_categories (category_name) VALUES ('fantasy') ON CONFLICT DO NOTHING ;              
INSERT INTO public.book_categories (category_name) VALUES ('detectives') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('science_fiction') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('action') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('russian_classic') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('english_classic') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('adventure') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('romantic_novel') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('horror') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('comic') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('humor') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('historical') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('biography') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('economy') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('popular_science') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('culture') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('art') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('dictionary') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('sports') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('medicine') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('cooking') ON CONFLICT DO NOTHING ;
INSERT INTO public.book_categories (category_name) VALUES ('children_literature') ON CONFLICT DO NOTHING ;

INSERT INTO public.authors (first_name, last_name) VALUES ('Джон', 'Р.Р. Толкиен') ON CONFLICT DO NOTHING ;
INSERT INTO public.books (title, author_id, book_category_id, year, book_info, price, discount, unit_in_stock, hyperlink) VALUES ('Хранители кольца', 1 , 1 , 1954 , 'Трилогия «Властелин Колец» бесспорно возглавляет список «культовых» книг ХХ века' , 349 , 0, 100, 'https://cv1.litres.ru/pub/c/elektronnaya-kniga/cover_415/128316-dzhon-tolkin-hraniteli-kolca.webp' ) ON CONFLICT DO NOTHING ;
INSERT INTO public.books (title, author_id, book_category_id, year, book_info, price, discount,  unit_in_stock, hyperlink) VALUES ('Две твердыни', 1 , 1 , 1954 , 'Перед вами трилогия «Властелин Колец». Своеобразная «Библия от фэнтези».' , 349 , 0 , 100 , 'https://cv5.litres.ru/pub/c/elektronnaya-kniga/cover_415/67601652-dzhon-tolkin-dve-tverdyni-67601652.webp') ON CONFLICT DO NOTHING ;
INSERT INTO public.books (title, author_id, book_category_id, year, book_info, price, discount, unit_in_stock, hyperlink) VALUES ('Возвращение короля', 1 , 1 , 1955 , 'Трилогия «Властелин Колец» бесспорно возглавляет список «культовых» книг ХХ века' , 349 , 0 , 100 , 'https://cv1.litres.ru/pub/c/elektronnaya-kniga/cover_415/128318-dzhon-tolkin-vozvraschenie-korolya-128318.webp') ON CONFLICT DO NOTHING ;
INSERT INTO public.books (title, author_id, book_category_id, year, book_info, price, discount, unit_in_stock, hyperlink) VALUES ('Хоббит или туда и обратно', 1 , 1 , 1937 , 'Перед вами – самая любимая волшебная сказка для детей в самом любимом оформлении Михаила Беломлинского и в прекрасном переводе Натальи Рахмановой, знакомом каждому.' , 379 , 0, 100 , 'https://cv5.litres.ru/pub/c/elektronnaya-kniga/cover_415/122257-dzhon-tolkin-hobbit-ili-tuda-i-obratno.webp') ON CONFLICT DO NOTHING ;
INSERT INTO public.authors (first_name, last_name) VALUES ('Сергей', 'Лукьяненко') ON CONFLICT DO NOTHING ;
INSERT INTO public.books (title, author_id, book_category_id, year, book_info, price, discount, unit_in_stock, hyperlink) VALUES ('Месяц за Рубиконом', 2 , 3 , 2021 , 'Продолжении серии «Измененные» – в новой книге «Месяц за Рубиконом».' , 379 , 0 , 300 , 'https://cv9.litres.ru/pub/c/elektronnaya-kniga/cover_415/66732098-sergey-lukyanenko-mesyac-za-rubikonom.webp') ON CONFLICT DO NOTHING ;
INSERT INTO public.authors (first_name, last_name) VALUES ('Дарья', 'Донцова') ON CONFLICT DO NOTHING ;
INSERT INTO public.books (title, author_id, book_category_id, year, book_info, price, discount, unit_in_stock, hyperlink) VALUES ('Курятник в пентхаусе', 3 , 2 , 2022 , 'Сыщики взялись за дело и окунулись вовсе не в чистую, а в очень грязную и мутную воду.' , 279 , 0 , 300 , 'https://cv0.litres.ru/pub/c/elektronnaya-kniga/cover_415/68340500-darya-doncova-kuryatnik-v-penthause.webp') ON CONFLICT DO NOTHING ;
INSERT INTO public.authors (first_name, last_name) VALUES ('Стивен', 'Кинг') ON CONFLICT DO NOTHING ;
INSERT INTO public.books (title, author_id, book_category_id, year, book_info, price, discount, unit_in_stock, hyperlink) VALUES ('Билли Саммерс', 4 , 9 , 2021 , 'Билли Саммерс – профессиональный киллер с жестким моральным кодексом: он принимает заказы только на действительно «плохих парней».' , 499 , 0 , 500 , 'https://cv6.litres.ru/pub/c/elektronnaya-kniga/cover_415/67303161-stiven-king-billi-sammers.webp') ON CONFLICT DO NOTHING ;
INSERT INTO public.authors (first_name, last_name) VALUES ('Михаил', 'Зыгарь') ON CONFLICT DO NOTHING ;
INSERT INTO public.books (title, author_id, book_category_id, year, book_info, price, discount, unit_in_stock, hyperlink) VALUES ('Империя должна умереть', 5 , 12 , 2017 , 'Глава за главой, через живые истории людей, Михаил Зыгарь показывает, как империя неуклонно движется к катастрофе и почему ничто не может ее спасти.' , 449 , 0 , 450 , 'https://cv3.litres.ru/pub/c/elektronnaya-kniga/cover_415/25922438-mihail-zygar-imperiya-dolzhna-umeret.webp') ON CONFLICT DO NOTHING ;
INSERT INTO public.authors (first_name, last_name) VALUES ('Марк', 'Мэнсон') ON CONFLICT DO NOTHING ;
INSERT INTO public.books (title, author_id, book_category_id, year, book_info, price, discount, unit_in_stock, hyperlink) VALUES ('Will', 6 , 13 , 2021 , 'Вдохновитесь мемуарами Уилла Смита – человека, у которого можно научиться преодолевать трудности, идти к своей цели и быть откровенным с самим собой.' , 579 , 0 , 450 , 'https://cv3.litres.ru/pub/c/audiokniga/cover_415/67254938-uill-smit-will-chemu-mozhet-nauchit-nas-prostoy-paren-stavshiy-sa-67254938.webp') ON CONFLICT DO NOTHING ;
INSERT INTO public.authors (first_name, last_name) VALUES ('Фрэнк', 'Герберт') ON CONFLICT DO NOTHING ;
INSERT INTO public.books (title, author_id, book_category_id, year, book_info, price, discount, unit_in_stock, hyperlink) VALUES ('Дюна', 7 , 3 , 1965 , '«Дюна» считается одним из величайших научно-фантастических произведений всех времен и часто упоминается как самый продаваемый роман данного жанра в истории' , 549 , 0.2 , 300, 'https://cv9.litres.ru/pub/c/elektronnaya-kniga/cover_415/55339991-frenk-gerbert-duna.webp') ON CONFLICT DO NOTHING ;